### ISSUE TITLE
"Play next" not working and "add to queue" working erratically

### ISSUE THREAD

**Issue by fbrcc** [jaedb/Iris#141] opened 2017-07-01 23:08 UTC
The "play next" feature is not working, while the "add to queue" sometimes doesn't work. I'm currently running ubuntu 16.04 64bits and Google Chrome 59.0.3071.86. Let me know if you need any more info. 
Thanks!

**Comment by jaedb** [comment] 2017-07-01 23:36
More information would be useful; eg are you playing a track from a playlist, artist, album, etc? A video of your exact steps would be super helpful.

Also try debugging to look for any errors. See [Debugging](https://github.com/jaedb/Iris/wiki/Advanced#debugging)

**Comment by ansraliant** [comment] 2017-07-25 17:51
I had the same issue, until I found that I had to click one time the song, and then select Play Next. Maybe it helps you @fbrcc

**Comment by jaedb** [comment] 2017-07-25 18:50
@ansraliant is this only experienced when right-clicking a track (eg using the context menu)? Do you think this could be a duplicate of #101?

**Comment by ansraliant** [comment] 2017-07-25 19:11
Yes, I think it's a duplicate. @alladinsane mentioned the same behavior on #101. 

_Sent from my Sony F8332 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jaedb** [comment] 2017-07-28 05:38
Resolved in #101

**Closed by jaedb** 2017-07-28 05:38 UTC
Labels: discussion/unactionable
