### ISSUE TITLE
Websocket not working when running behind Nginx reverse proxy

### ISSUE THREAD

**Issue by LickABrick** [jaedb/Iris#401] opened 2019-05-13 19:29 UTC
**Describe the bug**
When running behind a Nginx reverse proxy the websocket does not seem to work.

**To Reproduce**
1. Go to 'externaldomain.example.com'

**Expected behavior**
A connection to the mopidy-iris can be made

**Environment details:**
 - OS: [Raspbian]
 - Browser [Chrome]
 - Iris version [3.37.0]

Running nginx config from the wiki

**Additional context**
When going the the direct IP of the mopidy server and entering the local IP everything works fine.

**Comment by jaedb** [comment] 2019-05-26 08:33
Duplicate of #361

**Closed by jaedb** 2019-05-26 08:33 UTC
Labels: bug
