### ISSUE TITLE
[Feature request] Save to your music

### ISSUE THREAD

**Issue by robinvd** [jaedb/Iris#222] opened 2017-10-26 20:14 UTC
I have not found a way in Iris to add a single song to 'Your music/Songs'. In the spotify web client in the right click context menu there is 'Save to your music'.

![](https://i.imgur.com/HAJhFHo.png)

![](https://i.imgur.com/vM85NBH.png)

Maybe to add to playlist menu could include 'your music/songs'

**Comment by jaedb** [comment] 2017-11-14 08:06
Duplicate of #215

**Closed by jaedb** 2017-11-14 08:06 UTC
