### ISSUE TITLE
Browse always returns the message "Nothing can be found" messages

### ISSUE THREAD

**Issue by pjones1063** [jaedb/Iris#719] opened 2021-03-23 11:39 UTC
Browse returns no results at all in any content type - files, local media and tune in.    I can see entries in any other section (as expected) - artists, albums, tracks, etc.   This works as expected.

# Below is my modify.conf - Very much 'just out of the box' installation:

[http]
enabled = true
hostname = 0.0.0.0
zeroconf = ""

[audio]
output = alsasink
mixer = software

[local]
media_dir = /mopidy/Music
enabled = true
scan_follow_symlinks = true

[file]
media_dirs = /mopidy
follow_symlinks = true

[spotify]
enabled = true
bitrate = 96

[youtube]
enabled = true

[gmusic]
enabled = true

[tune-in]
enable = true

# And My  "sudo mopidyctl deps" 

Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf deps" as user mopidy
WARNING  [MainThread] mopidy.config Ignoring config section 'tune-in' because no matching extension was found
WARNING  [MainThread] mopidy.config Ignoring config section 'youtube' because no matching extension was found
WARNING  [MainThread] mopidy.config Ignoring config section 'gmusic' because no matching extension was found
Executable: /usr/bin/mopidy
Platform: Linux-5.10.17-v7l+-armv7l-with-debian-10.8
Python: CPython 3.7.3 from /usr/lib/python3.7
Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
Mopidy-Iris: 3.57.0 from /usr/local/lib/python3.7/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/local/lib/python3.7/dist-packages
    setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
Mopidy-Muse: 0.0.24 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/local/lib/python3.7/dist-packages
    setuptools: 40.8.0 from /usr/lib/python3/dist-packages
Mopidy-TuneIn: 1.1.0 from /usr/lib/python3/dist-packages
Mopidy-MPD: 3.1.0 from /usr/lib/python3/dist-packages
Mopidy-Scrobbler: 2.0.1 from /usr/lib/python3/dist-packages
Mopidy-Mobile: 1.10.0 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
Mopidy-Spotify: 4.1.0 from /usr/lib/python3/dist-packages
Mopidy-ALSAMixer: 2.0.1 from /usr/lib/python3/dist-packages
Mopidy-Local: 3.2.0 from /usr/lib/python3/dist-packages
Mopidy-MusicBox-Webclient: 3.1.0 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/local/lib/python3.7/dist-packages
    setuptools: 40.8.0 from /usr/lib/python3/dist-packages
GStreamer: 1.14.4.0 from /usr/lib/python3/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.30.4
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad

**Comment by pjones1063** [comment] 2021-03-23 20:12
This is a dup of 718 and a bug for sure. 

This fixed it for me:
sudo pip3 install --upgrade mopidy-iris==3.56.1

**Comment by jaedb** [comment] 2021-03-24 07:15
@pjones1063 please check for existing issues before creating a new one. Closing as duplicate of #718.

**Closed by jaedb** 2021-03-24 07:15 UTC
Labels: bug
