### ISSUE TITLE
Check if Spotify is enabled before refreshing the token

### ISSUE THREAD

**Issue by maxerenberg** [jaedb/Iris#592] opened 2020-08-23 02:31 UTC
**Describe the bug**
Iris shows a "Loading Spotify lists" banner forever and also fails to display an error message. Here is a screenshot:
![image](https://user-images.githubusercontent.com/34190303/90969206-f053c980-e4c3-11ea-9102-41cf60b3a50c.png)

**To Reproduce**
1. Make sure Spotify is disabled in Mopidy.
2. Start Mopidy, open Iris and go to the "Playlists" page.
3. Iris tries to load Spotify playlists even though Spotify was disabled.

**Expected behavior**
Iris should not try to load Spotify playlists when Spotify is not enabled in the first place.

**Environment details:**
 - OS: Ubuntu 20.04
 - Browser: Firefox 79.0
 - Iris version: 3.52.2

**Additional context**
There are actually two problems here - one is that Spotify playlists are being fetched when they shouldn't be, and the second problem is that a SyntaxError object is given to the Google Analytics library when it expects a String. The SyntaxError originates from the Mopidy backend raising an Exception when it tries to access `self.config['spotify']` (KeyError), so it returns 0 bytes to the browser, and then we call JSON.parse on an empty string (spotify/actions.js), and we then dispatch the Error object to coreActions.handleException (in getLibraryPlaylistsProcessor).

To fix the Spotify problem, LibraryPlaylists.js needs to check if Spotify is enabled before calling getLibraryPlaylists. A possible solution is
```
getSpotifyLibrary = () => {
    const {
      source,
      spotify_available,
      spotify_library_playlists_status,
      spotifyActions: {
        getLibraryPlaylists,
      },
    } = this.props;

    if (!(source === 'spotify' ||
         (source === 'all' && spotify_available))) return;
    if (spotify_library_playlists_status === 'finished') return;
    if (spotify_library_playlists_status === 'started') return;

    getLibraryPlaylists();
  };
```
To fix the GA problem, we could explicitly cast to a String in core/actions.js, e.g.
```
export function handleException(message, data = {}, description = null, show_notification = true) {
  if (!message) {
    if (data.message) {
      message = data.message;
    } else if (data.error.message) {
      message = data.error.message;
    }
  }
  if (typeof message !== 'string') {
    message = String(message);
  }
  if (!description) {
  ...
```

**Comment by jaedb** [comment] 2020-08-24 09:11
Duplicate of #565. I'm going to close this issue in favor of #565, but your issue more accurately describes the Spotify aspect - thanks for this. I have added catching of this on both server-side and front-end to properly handle this. It'll be included in the next release.

And very good points on GA string casting, cheers.

**Closed by jaedb** 2020-08-24 09:11 UTC
Labels: bug
