### ISSUE TITLE
cannot add local file to local playlist

### ISSUE THREAD

**Issue by LiranSX** [jaedb/Iris#663] opened 2020-11-29 15:19 UTC
using iris version 3.54.2 with chrome incognito/non incognito, and firefox - with all the following scenario is reproducible:

1. from left panel - "Browse" -> "Files" - going to local files
2. right click on an mp3 file -> "Add To Playlist"
3. select the playlist (all local playlists) -> nothing happens and  the file was not added to the playlist

i'm using iris only for local files playback - no spotify or other external source add on installed.
I've enabled debug mode and at the moment i add the file to the playlist - this is the console output:

:6680/iris/library/browse/file%3A%2F%2F%2Fmedia%2Fusb%2FTracks%2FAmbience%2FArcade%20Rooms:1 Uncaught (in promise) ./node_modules/mopidy/src/mopidy.js.Mopidy.ConnectionError {name: "ConnectionError", message: "WebSocket closed", closeEvent: CloseEvent}closeEvent: CloseEvent {isTrusted: true, wasClean: true, code: 1005, reason: "", type: "close", …}bubbles: falsecancelBubble: falsecancelable: falsecode: 1005composed: falsecurrentTarget: WebSocket {url: "ws://192.168.0.186:6680/mopidy/ws/", readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}defaultPrevented: falseeventPhase: 0isTrusted: truepath: []reason: ""returnValue: truesrcElement: WebSocket {url: "ws://192.168.0.186:6680/mopidy/ws/", readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}target: WebSocket {url: "ws://192.168.0.186:6680/mopidy/ws/", readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}timeStamp: 154491.39999994077type: "close"wasClean: true__proto__: CloseEventmessage: "WebSocket closed"name: "ConnectionError"__proto__: Error
Promise.then (async)
(anonymous) @ middleware.js:1212
Promise.then (async)
(anonymous) @ middleware.js:1199
(anonymous) @ middleware.js:238
(anonymous) @ middleware.js:765
(anonymous) @ index.js:11
(anonymous) @ redux.js:477
(anonymous) @ ContextMenu.js:424
onClick @ ContextMenu.js:797
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:71
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:306
executeDispatch @ react-dom.development.js:389
executeDispatchesInOrder @ react-dom.development.js:414
executeDispatchesAndRelease @ react-dom.development.js:3278
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3287
forEachAccumulated @ react-dom.development.js:3259
runEventsInBatch @ react-dom.development.js:3304
runExtractedPluginEventsInBatch @ react-dom.development.js:3514
handleTopLevel @ react-dom.development.js:3558
batchedEventUpdates$1 @ react-dom.development.js:21871
batchedEventUpdates @ react-dom.development.js:795
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
sentryWrapped @ helpers.js:71

**Comment by jaedb** [comment] 2020-11-30 06:58
Duplicate of #657

**Closed by jaedb** 2020-11-30 06:58 UTC
Labels: bug
