### ISSUE TITLE
mopidy-dleyna: track info not showing 

### ISSUE THREAD

**Issue by mczerski** [jaedb/Iris#661] opened 2020-11-26 22:55 UTC
In search results or now playing track info is clicked for mopidy-dleyna track, iris is not showing track info. instead error page is displayed.

**To Reproduce**
1. install mopidy-dleyna baclend
2. setup dlna server accessible by mopidy
3. search for tracks from mopidy-dleyna backend
4. click on the track info of the mopidy-dleyna track
5. error page is displayed

**Expected behavior**
Iris should display track info page

**Console log**
nothing is showed in the console log

**Screenshots**
![iris_dleyna_track_info](https://user-images.githubusercontent.com/2772080/100395850-da195480-3042-11eb-921d-293fc74ed9c9.png)

**Environment details:**
 - OS: client: linux mint 20.0, server armbian buster
 - Browser firefox
 - Iris version 3.54.2

**Comment by kingosticks** [comment] 2020-11-26 23:05
Do other frontends/webclients work correctly i.e. is this a problem specific to Iris?

**Comment by mczerski** [comment] 2020-11-26 23:10
musicbox-webclient is showing track info:
![musicbox_dleyna_track_info](https://user-images.githubusercontent.com/2772080/100396280-e3a3bc00-3044-11eb-936f-ba436e589767.png)

**Comment by morithil** [comment] 2020-12-31 01:41
I am also experiencing this issue unfortunately, same as above

**Comment by jaedb** [comment] 2021-01-05 08:08
I have spent a fair bit of time investigating this, and ultimately this is a limitation of how Mopidy-dLeyna constructs their URIs. Most providers follow a consistent syntax of `provider:type:id`, eg `spotify:track:123456789`.

dLeyna however uses a folder-ish structure, I assume this is to reflect multiple-server support. For example an album would be `dleyna://uuid:abc123/def456` and a track `dleyna://uuid:abc123/xyz987`; there is zero way for Iris to differentiate between albums, artists, tracks and so-on.

This is critical for Iris to determine which view to use when rendering the information provided by Mopidy. The nuts and bolts of the issue is that Iris uses `uri` as a source of truth for routing, rendering and type identification. This is by design, but when a backend doesn't provide this information in its URI then we encounter issues.

At this stage I cannot see a simple fix. In a perfect world, Mopidy-dLeyna would be updated to use a URI schema like that of Spotify, but I recognize this is probably an issue wider than just Mopidy-dLeyna.

The alternative is to overhaul how Iris identifies URI types:
1. Link is generated to type-agnostic fetcher (eg `/iris/fetch/spotify:track:1234`)
2. Fetch component calls fetch to provider, while showing loader
3. On response, determine type and route to appropriate view

The downside of this is that it's a large piece of work (weeks), so it is not likely to happen in the short term.

**Comment by kingosticks** [comment] 2021-01-05 12:28
For what it is worth, Mopidy's URIs are supposed to be opaque values and no one but the backend that created them should try and derive any meaning from them (with the exception of the scheme part). I can only find that explicitly documented for `Ref` URIs (and also quite buried) so we should make that much clearer. It's purely an implementation detail that you happen to be able to reliably infer type information for URIs in backends like Mopidy-Spotify, there is no reason that won't change in the future.

Clients should be using the type info provided in our models. If they only have a URI, they will need to do some kind of lookup to obtain that info. I think that is the overhaul you describe.

**Comment by jaedb** [comment] 2021-01-09 03:04
For pure Mopidy API calls this is fine, because there is only one endpoint to query URIs (`library.lookup`). However this causes headaches for assets with enhanced information from third-party APIs (like that of Spotify), whose endpoints change type-to-type. So you need to know the URI type before you can query it.

This can be worked around, but it does make things a lot more complex.

**Comment by jaedb** [comment] 2021-01-28 08:08
The next issue here is that dLeyna lowercase-encodes it's URIs, which is not how most browsers handle encoding. It doesn't sound like much, but when Iris encodes the URI it will use the standardised `%3A` to represent `:`. dLeyna however will encode this as `%3a`, causing the track to never load in Iris.

See https://github.com/tkem/mopidy-dleyna/issues/72

**Comment by jaedb** [comment] 2021-02-20 19:07
Resolved in `3.56.0`

**Closed by jaedb** 2021-02-20 19:07 UTC
Labels: P1, bug, confirmed, in progress
