### ISSUE TITLE
Iris not showing up in list of extenstions

### ISSUE THREAD

**Issue by dmdamen** [jaedb/Iris#175] opened 2017-08-20 14:10 UTC
I'm running mopidy 2.1.0 on raspian jessie lite. I've been able to install moped without any issues but I can't seem to get Iris installed. It is not even shoing up in the list of extentions.

**Comment by jaedb** [comment] 2017-08-20 21:13
Did you receive any errors during the installation of either mopidy or Iris? What about when you try to start mopidy? This will provide the information to identify where the issue lies.

**Comment by dylono96** [comment] 2017-08-21 09:15
I have the same issue, it is installed on my pi but it doesnt show up in my extension list.

**Comment by jaedb** [comment] 2017-08-22 03:21
Possibly related #178

**Comment by dylono96** [comment] 2017-08-22 08:40
to me it shows the exact same, I wanna try the spotipy solution but is this know to work for sure?

**Comment by dylono96** [comment] 2017-08-22 08:53
nevermind, just installing spotipy worked for me as well.
I did not need extra configs. for me this issue can be closed.

**Comment by jaedb** [comment] 2017-08-25 21:24
@dmdamen if this fixes the problem for you, please close this issue.

**Comment by JonasPf** [comment] 2017-09-09 13:31
Same problem here. A quick test in the Python repl shows me that it is indeed missing spotipy:

```
>>> import mopidy_iris
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/__init__.py", line 7, in <module>
    import handlers
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/handlers.py", line 5, in <module>
    from spotipy import Spotify
ImportError: No module named spotipy
```

A simple: `sudo pip install spotipy` fixed the problem.

My guess is that this was caused by the following commit: https://github.com/jaedb/Iris/commit/0c134459ea46799f535a56fb5908629856f2f6e5#diff-2eeaed663bd0d25b7e608891384b7298

**Closed** 2017-09-10 15:28 UTC

**Comment by dmdamen** [comment] 2017-09-10 15:33
Thanks for the help. I'll retry as soon as I have the time.

**Comment by jaedb** [comment] 2017-09-10 20:04
@JonasPf thanks for that error log - that's all I needed to trace the issue and fix it properly.

We no longer use `spotipy` for authentication, so it is not a dependency of Iris anymore. `handlers.py` still imported `spotipy` which is why Iris was failing to load properly. I've since removed this and all is looking good.
