### ISSUE TITLE
[Feature request] Git-based code for installing updates on-the-fly

### ISSUE THREAD

**Issue by Hugomm** [jaedb/Iris#170] opened 2017-08-10 22:03 UTC
The upgrade button on settings page is not working. When it's clicked it does nothing.

![image](https://user-images.githubusercontent.com/14215939/29194127-8d453158-7e28-11e7-9435-5970919ec502.png)

**Comment by jaedb** [comment] 2017-08-10 22:25
I think you might find it _does_ do something, however to complete the upgrade you need to restart Mopidy.

The guts of the issue is that to apply updates Iris needs to be restarted, which means Mopidy needs to be restarted. So it's a python script trying to restart itself. Picture a dog chasing it's tail...

Other python-based applications use git to pull new releases, and only require restarts when installing a major release. This is where Iris is heading, but it's a big piece of work and is not currently planned.

**Comment by Hugomm** [comment] 2017-08-10 22:30
So how about a notification that you have to manually restart the system to apply the update?
Since this moment I thought the button did nothing so I was doing `pip install --upgrade Mopidy-Iris` and `reboot`

**Comment by jaedb** [comment] 2018-11-20 08:11
@Hugomm have the more recent versions of Iris resolved this issue for you?

**Comment by Hugomm** [comment] 2018-11-20 08:51
Hi @jaedb not using Modipy at the moment, can't report

**Comment by jaedb** [comment] 2019-02-08 00:37
Resolved by allowing `sudo` access and using the button from within Iris. This triggers a series of bash commands to upgrade and then restart Mopidy.

**Closed by jaedb** 2019-02-08 00:37 UTC
Labels: P3
