### ISSUE TITLE
order spotify playlists like spotify order no

### ISSUE THREAD

**Issue by tatoosh** [jaedb/Iris#213] opened 2017-10-04 09:10 UTC
It would be nice to sort the spotify playlists like the order no on spitify apps.
Thx , Tatoosh

**Comment by jaedb** [comment] 2017-10-04 18:23
Duplicate of the unresolvable #163.

Please read [before you log an issue](https://github.com/jaedb/Iris/wiki/Support#before-you-log-an-issue).

**Closed by jaedb** 2017-10-04 18:23 UTC
