### ISSUE TITLE
Iris "Play" does not play when Iris runs on Raspi Chromium or Firefox

### ISSUE THREAD

**Issue by martinklein** [jaedb/Iris#866] opened 2022-09-02 17:07 UTC
### Iris version

3.64.1

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

I just installed latest Version of Mopidy (3.3.0) on my Raspi 4 4GB with a new Raspian OS (Bullseye) with all updates.
I start mopidy with "sudo systemctl start mopidy" and open the Chromium Browser on the same Raspi and open Iris - Albums.
I click on any Album and Press "Play" nothing happens. Then I try the Play Button on the bottom of the screen (left of the progress bar) and this shows now "Pause" but plays nothing. Progress bar not moving.
But all tracks of the album are added to the "Now Playing" list. But also on this list when I select a track and "Play" nothing happens. But the selected track is again added to the "Now playing" list. I tried the same also with Firefox on the same Raspi with exactly same results.
When I start the same Iris remotely on any browser in Windows 11 in the same network everything works fine. When I select an Album and press "Play" the first track starts playing. When I start the same Iris from my browser on my Android device everything works fine.

Many thanks for your help
Regards. Martin Klein

[mopidy.conf.txt](https://github.com/jaedb/Iris/files/9479599/mopidy.conf.txt)

### Logs

```shell
react-dom.development.js:24994 Download the React DevTools for a better development experience: https://fb.me/react-devtools
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'outputs, queue, queue_metadata, current_track, pinned, seeds_resolved, radio, current_tracklist, _persist, next_track_uri'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'language, theme, smooth_scrolling_enabled, hotkeys_enabled, playback_controls_touch_enabled, allow_reporting, wide_scrollbar_enabled, hide_scrollbars, slim_mode, suppressed_broadcasts, grid_glow_enabled, sort, window_title, uri_schemes_search_enabled, initial_setup_complete, modal, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'host, port, ssl, current_server, servers, mute, volume, progress, play_state, uri_schemes, library_albums_uri, library_artists_uri, library_tracks_uri, connecting, restart_running, upgrade_running, consume, random, repeat, time_position, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'enabled, country, locale, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'username, client_id, version, config, connecting, shared_config, commands, pinned, upgrading, _persist, connection_id'
2autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'authorization_url, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'enabled, connected, host, port, ssl, streams, groups, clients, server, commands, _persist'
warn.js:2 [react-ga] ReactGA.initialize must be called first or GoogleAnalytics should be loaded manually
warn @ warn.js:2
internalGa @ core.js:57
_gaCommand @ core.js:78
set @ core.js:192
(anonymous) @ App.js:176
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
performSyncWorkOnRoot @ react-dom.development.js:21737
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
(anonymous) @ react.js:61
dispatch @ redux.js:222
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
combination @ redux.js:459
rootReducer @ index.js:230
dispatch @ redux.js:213
(anonymous) @ middleware.js:660
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:55
(anonymous) @ middleware.js:203
(anonymous) @ middleware.js:932
(anonymous) @ middleware.js:2350
(anonymous) @ middleware.js:227
(anonymous) @ middleware.js:805
(anonymous) @ index.js:11
persist @ persistStore.js:114
persistStore @ persistStore.js:123
./src/js/store/index.js @ index.js:248
__webpack_require__ @ bootstrap:19
./src/js/index.js @ index.js:1
__webpack_require__ @ bootstrap:19
0 @ app.scss?df22:1
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
warn.js:2 [react-ga] ReactGA.initialize must be called first or GoogleAnalytics should be loaded manually
warn @ warn.js:2
internalGa @ core.js:57
_gaCommand @ core.js:78
pageview @ core.js:245
(anonymous) @ App.js:177
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
performSyncWorkOnRoot @ react-dom.development.js:21737
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
(anonymous) @ react.js:61
dispatch @ redux.js:222
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
combination @ redux.js:459
rootReducer @ index.js:230
dispatch @ redux.js:213
(anonymous) @ middleware.js:660
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:55
(anonymous) @ middleware.js:203
(anonymous) @ middleware.js:932
(anonymous) @ middleware.js:2350
(anonymous) @ middleware.js:227
(anonymous) @ middleware.js:805
(anonymous) @ index.js:11
persist @ persistStore.js:114
persistStore @ persistStore.js:123
./src/js/store/index.js @ index.js:248
__webpack_require__ @ bootstrap:19
./src/js/index.js @ index.js:1
__webpack_require__ @ bootstrap:19
0 @ app.scss?df22:1
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
77[Violation] 'message' handler took <N>ms
12[Violation] 'setTimeout' handler took <N>ms
8[Violation] 'setInterval' handler took <N>ms
middleware.js:291 [Violation] 'open' handler took 1343ms
9[Violation] 'click' handler took <N>ms
155The provided value 'stopped' is not a valid enum value of type MediaSessionPlaybackState.
instrument.js:109 {type: 'LOAD_LIBRARY', uri: 'local:directory?type=album', uriType: 'albums', options: {…}}
instrument.js:109 Restoring "local:directory?type=album" and 33 items from database
instrument.js:109 "local:album:md5:271c2382c05eb3caeb3759ab0e155465" already in index
[Violation] Forced reflow while executing JavaScript took 101ms
instrument.js:109 Restoring "local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/01.Come_Together_%282019_mix%29.flac" from database
instrument.js:109 "local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/01.Come_Together_%282019_mix%29.flac" already in index
[Violation] Forced reflow while executing JavaScript took 86ms
[Violation] 'contextmenu' handler took 215ms
App.js:203 [Violation] 'blur' handler took 187ms
instrument.js:109 "local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/01.Come_Together_%282019_mix%29.flac" already in index
```

**Comment by jaedb** [comment] 2022-09-03 23:38
This sounds like an issue playing the audio, rather than Iris adding them to the queue. What do you observe in your Mopidy logs when you walk through the replication steps?

**Comment by martinklein** [comment] 2022-09-04 08:49
Thanks for your comment.

This is the mopidy.log
Says that the audio device is used by another process. But nothing else is running.

Sep 02 16:19:56 mopidy systemd[1]: Starting Mopidy music server...
Sep 02 16:19:56 mopidy systemd[1]: Started Mopidy music server.
Sep 02 16:19:59 mopidy mopidy[577]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.1.1
Sep 02 16:19:59 mopidy mopidy[577]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
Sep 02 16:19:59 mopidy mopidy[577]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
Sep 02 16:19:59 mopidy mopidy[577]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
Sep 02 16:19:59 mopidy mopidy[577]: INFO     [MainThread] mopidy.config Loading config from command line options
Sep 02 16:20:00 mopidy mopidy[577]: INFO     [MainThread] mopidy.__main__ Enabled extensions: iris, m3u, stream, file, local, http, softwaremixer
Sep 02 16:20:00 mopidy mopidy[577]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
Sep 02 16:20:01 mopidy mopidy[577]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Sep 02 16:20:01 mopidy mopidy[577]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Sep 02 16:20:01 mopidy mopidy[577]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: LocalBackend, FileBackend, M3UBackend, StreamBackend
Sep 02 16:20:01 mopidy mopidy[577]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Sep 02 16:20:01 mopidy mopidy[577]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: IrisFrontend, HttpFrontend
Sep 02 16:20:01 mopidy mopidy[577]: INFO     [IrisFrontend-8] mopidy_iris.core Starting Iris 3.64.1
Sep 02 16:20:01 mopidy mopidy[577]: INFO     [HttpFrontend-10] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Sep 02 16:20:01 mopidy mopidy[577]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Sep 02 16:20:01 mopidy mopidy[577]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "alsasink device=hw:0,0"
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/01.Come_Together_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/02.Something_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/03.Maxwell%27s_Silver_Hammer_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/04.Oh%21_Darling_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/05.Octopus%27s_Garden_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/06.I_Want_You_%28She%27s_So_Heavy%29_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/07.Here_Comes_the_Sun_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/08.Because_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/09.You_Never_Give_Me_Your_Money_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/10.Sun_King_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/11.Mean_Mr_Mustard_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/12.Polythene_Pam_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/13.She_Came_In_Through_the_Bathroom_Window_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/14.Golden_Slumbers_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/15.Carry_That_Weight_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/16.The_End_%282019_mix%29.flac
Sep 02 16:25:19 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Sep 02 16:25:19 mopidy mopidy[577]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: local:track:The%20Beatles/Abbey%20Road%20%28anniversary%20edition%29/17.Her_Majesty_%282019_mix%29.flac
Sep 02 16:25:24 mopidy mopidy[577]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open audio device for playback. Device is being used by another application.
Sep 02 16:25:25 mopidy mopidy[577]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed

**Comment by jaedb** [comment] 2022-09-04 08:55
Ah, there could be a few factors here. I will direct you to a discussion talking about this error here: https://discourse.mopidy.com/t/mopidy-audio-gst-gstreamer-error-could-not-open-audio-device-for-playback/4581/16 this will provide a lot better insight and help than I can.

I'll close this issue here as it the problem is not related to Iris.

**Closed by jaedb** 2022-09-04 08:55 UTC
Labels: bug

**Comment by martinklein** [comment] 2022-09-05 15:20
James, I fixed this Problem.

In chromium Browser the Tab where iris runs must be right-clicked. In the
context menu you have to click "Mute Tab". This closes the "Audio process"
that otherwise occupies the audio hardware which is reorted in the mopidy
log file.

Could you please add this as a closing comment to help others.

And could this be added to the iris Dokumentation.

With kind regards
Martin Klein

James Barnsley ***@***.***> schrieb am So., 4. Sep. 2022,
10:55:
