### ISSUE TITLE
Iris unaccessible, 404

### ISSUE THREAD

**Issue by PureTryOut** [jaedb/Iris#871] opened 2022-11-17 16:22 UTC
### Iris version

3.65.0

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Other

### What happened?

I'm trying to run Iris but although Mopidy launches fine (and the log says Iris is started too) when I try to access Iris in the browser I just get a 404 page. The log shows nothing of interest.

This happens both when I try the official Docker image but with `debian:bookworm` as a base image instead and with a custom Alpine Linux-based image. ~~The official image as is works just fine.~~ No it doesn't, every image with the latest Iris is broken and according to reports further in this thread even without Docker it's broken.

### Logs

```shell
INFO     2022-11-17 16:19:12,878 [21:MainThread] mopidy.__main__
  Starting Mopidy 3.3.0
INFO     2022-11-17 16:19:12,902 [21:MainThread] mopidy.config
  Loading config from builtin defaults
INFO     2022-11-17 16:19:12,903 [21:MainThread] mopidy.config
  Loading config from file:///config/mopidy.conf
INFO     2022-11-17 16:19:12,904 [21:MainThread] mopidy.config
  Loading config from command line options
INFO     2022-11-17 16:19:12,907 [21:MainThread] mopidy.internal.path
  Creating dir file:///var/lib/mopidy/.cache/mopidy
INFO     2022-11-17 16:19:13,123 [21:MainThread] mopidy.__main__
  Enabled extensions: mpd, softwaremixer, http, m3u, iris, stream, file
INFO     2022-11-17 16:19:13,123 [21:MainThread] mopidy.__main__
  Disabled extensions: local, spotify
WARNING  2022-11-17 16:19:13,123 [21:MainThread] mopidy.__main__
  Found local configuration errors. The extension has been automatically disabled:
WARNING  2022-11-17 16:19:13,123 [21:MainThread] mopidy.__main__
    local/media_dir must be set.
WARNING  2022-11-17 16:19:13,123 [21:MainThread] mopidy.__main__
  Found spotify configuration errors. The extension has been automatically disabled:
WARNING  2022-11-17 16:19:13,123 [21:MainThread] mopidy.__main__
    spotify/username must be set.
WARNING  2022-11-17 16:19:13,123 [21:MainThread] mopidy.__main__
    spotify/password must be set.
WARNING  2022-11-17 16:19:13,124 [21:MainThread] mopidy.__main__
    spotify/client_id must be set.
WARNING  2022-11-17 16:19:13,124 [21:MainThread] mopidy.__main__
    spotify/client_secret must be set.
WARNING  2022-11-17 16:19:13,124 [21:MainThread] mopidy.__main__
  Please fix the extension configuration errors or disable the extensions to silence these messages.
INFO     2022-11-17 16:19:13,332 [21:MainThread] mopidy.commands
  Starting Mopidy mixer: SoftwareMixer
INFO     2022-11-17 16:19:13,333 [21:MainThread] mopidy.commands
  Starting Mopidy audio
INFO     2022-11-17 16:19:13,334 [21:MainThread] mopidy.commands
  Starting Mopidy backends: FileBackend, M3UBackend, StreamBackend
INFO     2022-11-17 16:19:13,338 [21:MainThread] mopidy.internal.path
  Creating dir file:///var/lib/mopidy/m3u
INFO     2022-11-17 16:19:13,344 [21:Audio-2 (_actor_loop)] mopidy.audio.actor
  Audio output set to "audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo"
INFO     2022-11-17 16:19:13,344 [21:MainThread] mopidy.commands
  Starting Mopidy core
INFO     2022-11-17 16:19:13,351 [21:MainThread] mopidy.commands
  Starting Mopidy frontends: MpdFrontend, HttpFrontend, IrisFrontend
INFO     2022-11-17 16:19:13,351 [21:MainThread] mopidy_mpd.actor
  MPD server running at [::ffff:0.0.0.0]:6600
INFO     2022-11-17 16:19:13,352 [21:HttpFrontend-9 (_actor_loop)] mopidy.http.actor
  HTTP server running at [::ffff:0.0.0.0]:6680
INFO     2022-11-17 16:19:13,352 [21:IrisFrontend-10 (_actor_loop)] mopidy_iris.core
  Starting Iris 3.65.0
INFO     2022-11-17 16:19:13,352 [21:MainThread] mopidy.commands
  Starting GLib mainloop
INFO     2022-11-17 16:19:13,356 [21:IrisFrontend-10 (_actor_loop)] mopidy.internal.path
  Creating dir file:///var/lib/mopidy/iris
INFO     2022-11-17 16:19:13,356 [21:HttpServer] mopidy.internal.path
  Creating dir file:///var/lib/mopidy/http
```

**Comment by fmarzocca** [comment] 2022-11-17 16:35
Are you pointing to the right url? http://<your-server>:6680/iris  ?

**Comment by PureTryOut** [comment] 2022-11-17 17:51
Obviously :wink:  Yes, I am. And with the default config I even get automatically redirected to it because Iris is set as the default app for the HTTP extension.

**Comment by PureTryOut** [comment] 2022-11-17 18:50
The page is really barebones :sweat_smile: 

![Screenshot_20221117_194931](https://user-images.githubusercontent.com/1565836/202532750-56501603-a34c-49b3-b374-399f2450f8e2.jpg)

The URL is just http://localhost:6680/iris/.

**Comment by jaedb** [comment] 2022-11-18 22:48
> ...The official image as is works just fine.
Just so I understand this more, are you saying the issue is isolated to your customisation? Or can it be replicated with the official Docker image and PyPi distribution?

**Comment by PureTryOut** [comment] 2022-11-20 10:22
Well, yeah. But the simplest customization it happens with is literally just changing the official Docker image to be based on Debian Bookworm rather than Debian Buster.

That's literally just the following:

```
diff --git a/Dockerfile b/Dockerfile
index 983170fb..16d1877f 100755
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM debian:buster
+FROM debian:bookworm
 
 # Switch to the root user while we do our changes
 USER root
@@ -23,7 +23,6 @@ RUN apt-get update \
     build-essential \
     libdbus-glib-1-dev \
     libgirepository1.0-dev \
-    dleyna-server \
     sudo \
   && rm -rf /var/lib/apt/lists/*
```

(`dleyna-server` being removed as it's not present in newer Debian versions anymore)

**Comment by nawordar** [comment] 2022-11-23 08:01
It also happens with the [AUR package](https://aur.archlinux.org/packages/mopidy-iris). The [install script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mopidy-iris) is very simple so there is little that can go wrong on this part.

I tried rebuilding (`paru -S --rebuild mopidy-iris`) and disabling all non-default extensions except Iris, but to no avail

**Comment by PureTryOut** [comment] 2022-11-25 07:32
A computer restart? Interesting, doesn't help here sadly...

The annoying thing is that there is no obvious error in the logs so I have no clue where to even begin debugging this.

Any clue what is up @jaedb? Since even the official Docker image straight from Dockerhub doesn't work?

**Comment by jaedb** [comment] 2022-11-25 08:12
Are you able to have a crack at replicating this outside of Docker? Ie by just installing with pip. And to be sure, you're definitely not using a proxy?

**Comment by PureTryOut** [comment] 2022-11-28 14:11
It works fine outside of Docker using the Pip package.

And yes I'm definitely not using a proxy, just accessing it via `localhost:6680`.

**Comment by jojo141185** [comment] 2022-12-04 14:42
I got the same problem "404: Not Found" since upgrade to Iris v3.65. 
I'm running Mopidy with Mopidy-Iris on a docker container with Debian 11 Bullseye image behind a HTTP reverse proxy called traefik. As jaedb has already pointed out it seems to be related with the changes how base_url is configured. 
After downgrading to v3.64 Mopidy-Iris is running again.

**Comment by jaedb** [comment] 2022-12-10 17:51
Ah I have a theory - and its to do with built files not existing in the Docker after they were removed from the Iris repository (see https://github.com/jaedb/Iris/commit/310fe0464d7585b636c4460571b115e804540f97). Instead they rely on being built during the GitHub Workflow, but this doesn't seem to be happening as expected.

I'll investigate further.

**Comment by polcape** [comment] 2022-12-11 18:23
Hello,

same error with official jaedb/iris docker images.

Is there a workaround?

Thanks

**Comment by PureTryOut** [comment] 2022-12-11 19:25
If you're read the rest of the issue, which you seemingly didn't, then you've seen that we already determined it's also broken in the official images and that there is no known workaround as of yet 😉 Well, besides downgrading to an older version that is.

**Comment by polcape** [comment] 2022-12-11 19:41
> If you're read the rest of the issue, which you seemingly didn't, then you've seen that we already determined it's also broken in the official images and that there is no known workaround as of yet wink Well, besides downgrading to an older version that is.

Thanks @PureTryOut I read the issue but I dind't understand there isn't workaround. I subscribe to get update.

**Comment by jaedb** [comment] 2022-12-11 19:53
The immediate fix is to install from pip (rather than cloning this repository, which doesn't include built files). Do this by adding `Mopidy-Iris` to the list of `pip` packages, or by adding `Mopidy-Iris` to your `PIP_PACKAGES` environment variable.

**Comment by shadowking001** [comment] 2022-12-22 23:14
@jaedb right now your trick is not working on my setup. My compose file :

```
version: "2.1"
services:

  iris-snapserver:
     container_name: iris-snapserver
     image: jaedb/snapserver
     networks:
        - net-proxy
     ports:
        # stream
        - 1704:1704
        # tcp
        #- 1705:1705
        # http
        - 1780:1780
     volumes:
        - tmp:/tmp
        - /opt/iris-snapserver/snapserver.conf:/etc/snapserver.conf
        - /opt/iris-snapserver/mopidy_meta.py:/usr/share/snapserver/plug-ins/mopidy_meta.py
      
  iris-mopidy:
     image: jaedb/iris
     container_name: iris-mopidy
     networks:
        - net-proxy
     environment:
        - PIP_PACKAGES=Mopidy-Local Mopidy-Iris
     depends_on:
        - iris-snapserver
     ports:
        # mpd
        #- 6600:6600
        # http
        - 6680:6680
     volumes:
        # iris-specific storage
        - /opt/iris-mopidy/data:/var/lib/mopidy/iris
        # playlists
        - /opt/iris-mopidy/m3u:/var/lib/mopidy/m3u
        # config
        - /opt/iris-mopidy/config/mopidy.conf:/config/mopidy.conf:ro
        # music files
        - music:/var/lib/mopidy/media:ro
        - tmp:/tmp
        
volumes:

   tmp:
   
   music:
      driver_opts:
         type: cifs
         o: 'username=media,password=HM52qFJkp5L^*Uzp@Zg!R^dfJXfCcK,uid=1000,gid=1000,vers=3.0'
         device: //192.168.100.100/music
         
networks:

   net-proxy:
      external: true
```

P.S : Adding "build" does not help either.

**Comment by a2nt** [comment] 2023-01-03 04:00
I had the same issue following manual installation instruction, but was able to fix it.
Just need to run npm commands before setup.py
```
npm i
npm build
npm prod
python3 ./setup.py install
```

**Comment by jaedb** [comment] 2023-01-23 07:19
This is now handled entirely in the Dockerfile build process, so the issue is fixed in all new builds

**Closed** 2023-01-23 07:20 UTC
Labels: bug
