### ISSUE TITLE
Unable to run Iris

### ISSUE THREAD

**Issue by jokerigno** [jaedb/Iris#235] opened 2017-11-21 10:25 UTC
## Expected behavior
run iris
## Actual behavior
file 404 (only with iris, no issue with others web clients)

I tried to update, remove, and reinstall iris without success.

I did't change anything in mopidy.conf: issue started few days ago.

## Steps to replicate
1.
2.

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [ ] Linux: Rasperry pi 3 with updater raspian (stretch)
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [ ] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [x ] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment] 2017-11-21 17:21
Potential duplicate of #234 

Please try updating your `mopidy.conf` to reflect the values in the [Installation guide](https://github.com/jaedb/Iris/wiki/Getting-started#configuration). Please note these may have changed since your last upgrade.

**Comment by jokerigno** [comment] 2017-12-02 11:33
I removed the config value in mopidy.conf and started working again.

**Comment by jaedb** [comment] 2017-12-02 19:16
@jokerigno That's great news. Glad you managed to get it sorted. I'll close this issue, but please re-open if you feel that the issue persists.

**Closed by jaedb** 2017-12-02 19:16 UTC
