### ISSUE TITLE
iris is not using album artwork provided by mopidy-local

### ISSUE THREAD

**Issue by tomaspapan** [jaedb/Iris#508] opened 2020-03-04 13:45 UTC
**Describe the bug**
It was already fixed in 3.43.3 but it is back in 3.45.1. For all the details see #496 

**To Reproduce**
see #496 

**Expected behavior**
see #496 

**Screenshots**
see #496 

**Environment details:**
see #496

**Comment by jaedb** [comment] 2020-03-04 17:55
Duplicate of https://github.com/jaedb/Iris/issues/496

**Closed by jaedb** 2020-03-04 17:55 UTC
Labels: bug
