### ISSUE TITLE
[Feature Request] Support GMusic artist and album libraries

### ISSUE THREAD

**Issue by wilburforce83** [jaedb/Iris#266] opened 2018-03-16 14:26 UTC
## Expected behavior
Albums and Artists available for browsing in "/iris/#/library/artists" + "/iris/#/library/albums"
## Actual behavior
blank library, everything is available in "browse" and "playlists". 

If I do a search using the main top left search, it is pulling gmusic albums and artists with images etc

## Steps to replicate
1. Browse folders, everything is there
2. Browse album or artist and it is blank -- I have checked the sources and it is selected as "all"

#### Operating systems affected
- [x ] Windows:
- [ ] Mac: 
- [x ] Linux: 
- [ ] iOS: 
- [x ] Andriod:
- [ ] Other:

#### Browsers affected
- [x ] Chrome: 
- [ x] Firefox: 
- [ x] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

## Additional details, debug data, logs, etc

Is there a way to add / or that I could add myself the inclusion of the gmusic library data to these menus?

## Before you submit
- [x ] Yes, I have tested this issue thoroughly
- [x ] Yes, I have attached screenshots and/or screencast of the issue in action
- [none to see ] Yes, I have included any relevant debug data and error logs

![image](https://user-images.githubusercontent.com/17556774/37525759-9ba4a5d2-2925-11e8-9d3c-cd5b099b33c5.png)

![image](https://user-images.githubusercontent.com/17556774/37525882-e3b3e86a-2925-11e8-888e-305b11c86863.png)

**Comment by jaedb** [comment] 2018-03-25 07:39
Unfortunately Google doesn't have a HTTP API to make this work as smoothly as the likes of Spotify. Depending on demand, this is something that could be built. So it's not a bug, so much as a feature request. Those interested, please voice your interest in this new functionality.

**Comment by armageddon421** [comment] 2018-04-22 16:33
I'd love this, too

**Comment by ajhodges** [comment] 2018-06-15 19:45
+1

**Comment by MaxG88** [comment] 2018-10-12 00:12
+1

**Comment by pdaire** [comment] 2018-10-12 17:35
👍

**Comment by mwalter416** [comment] 2018-10-15 02:15
+1

**Comment by jaedb** [comment] 2018-11-20 08:09
Released in `3.31.0`. I've managed to piggy-back the existing Mopidy backend. The only downside of this is known issues (eg invalid album artist URIs) exist, but this is a provider API issue rather than a frontend issue anyway.

**Closed by jaedb** 2018-11-20 08:09 UTC
Labels: accepting votes
