### ISSUE TITLE
When browsing local files, album art is permanently loading.

### ISSUE THREAD

**Issue by JDanen** [jaedb/Iris#926] opened 2023-10-05 12:22 UTC
Setup: Mopidy 3.4.1, Iris 3.6.0 (up to date at time of writing) and mopidy-local for the local music library. All running on a machine with an older version of antiX Linux (Based on Debian 10 Buster). Access attempted by various browsers on various systems, e.g. Pale Moon and Firefox ESR from a Debian system, and a relatively recent version of MS Edge on Windows 10.

Problem: When browsing the local library by albums, the album art (not embedded) is displayed, but in a "grayed out" mode, and has a loading indicator (spinning circle). This seems to be permanent - didn't solve within 30 min, which I would've expected to be enough to load a JPEG. 

So, what could be at fault?

**Comment by jaedb** [comment] 2023-10-10 08:04
This looks to be a duplicate of https://github.com/jaedb/Iris/issues/925

**Closed by jaedb** 2023-10-10 08:04 UTC
