### ISSUE TITLE
Option to sort tracks by source (e.g. Spotify first)

### ISSUE THREAD

**Issue by wuservices** [jaedb/Iris#238] opened 2017-12-13 00:13 UTC
I have a few sources like SoundCloud, YouTube, and Spotify set up. However, the Spotify track often show up last. Is it possible to make Spotify tracks come up first since they're the best quality?

I saw you can choose sources by search, but it'd be great to have a default result ordering for all users.

**Comment by jaedb** [comment] 2017-12-17 19:44
Duplicate of #198

**Closed by jaedb** 2017-12-17 19:44 UTC
